### ISSUE TITLE
Create a tag version

### ISSUE THREAD

**Issue by mmassaki** [khanlou/SKBounceAnimation#1]
Hi,
could you create a tag version, please?
I need a tag to add this component to CocoaPods repo.

**Comment by khanlou** [comment]
Here you are.

https://github.com/khanlou/SKBounceAnimation/tree/v1.0

**Comment by mmassaki** [comment]
Thank you!

I've pushed SKBounceAnimation podspec to Specs repo of CocoaPods.

**Comment by khanlou** [comment]
Thank you!

**Comment by bogardon** [comment]
the pod spec is old now:(

**Comment by khanlou** [comment]
Submitted a pull request to the CocoaPods folks.

Edit: it's already merged in, cool
