### ISSUE TITLE
ability to start the animation slow instead of fast

### ISSUE THREAD

**Issue by krummler** [khanlou/SKBounceAnimation#11]
Hello, 

First off, thanks for the code, it's really handy and result looks amazing.
Would it be difficult to add an option to start the animation slow, instead of at full speed?

**Comment by khanlou** [comment]
Because of the fact that the animation is calculated, it's not really possible to change specific parts of the animation curve. There certainly are things you can do, but if you're going for a natural feel, you should stick with the exponential decay that is built in. What kind of effect are you trying to create?

**Comment by krummler** [comment]
The decay works fine and that's not what I want to change, I'm referring to the start of the animation. The effect starts at full speed, where it would be really cool for the initial speed to be 0, and to 'ease in' the speed.

Please take a look at my awesome paint skills to explain what I mean ;)
![screen shot 2013-05-29 at 4 51 52 pm](https://f.cloud.github.com/assets/1032307/579317/557c3744-c86f-11e2-8d73-f51f5f2c0dce.png)

**Comment by khanlou** [comment]
In a word, no. The animation is based on the step response a second-order differential equation: this means we have a mass-spring-damper and instantaneously move its center to a new location, causing it to try to get to that location as fast as possible, resulting in the overshoot and the bounce. 

We could also solve this equation with an instantaneous velocity input, but this wouldn't have the effect you're looking for either. What you're going for may be best achieved by using two consecutive animations.

**Comment by krummler** [comment]
Thanks, that's what I'm going for now. I'm finding it's actually pretty difficult to transition from the first to the second animation without causing the view to 'jump' a bit.
