### ISSUE TITLE
Tag latest release

### ISSUE THREAD

**Issue by jai** [khanlou/SKBounceAnimation#14]
Hey there - could you tag the latest release please? Would like to get an updated podspec on Cocoapods.

**Comment by khanlou** [comment]
Tagged: https://github.com/khanlou/SKBounceAnimation/releases/tag/v1.0.5 

What's the current process for updating podspecs? Are we still doing fork-and-pull or is trunk up?

**Comment by jai** [comment]
Trunk is up - initial pods claim period is over, but you can still claim I believe.
