### ISSUE TITLE
Question - how does the math compare to a scrollview bounce?

### ISSUE THREAD

**Issue by mrjjwright** [khanlou/SKBounceAnimation#3]
I am curious how close the general idea of the math and approach of this bounce is to a UIScrollView bounce, or are they different ideas?

**Comment by khanlou** [comment]
So, UIScrollViews bounce in a really specific way: you can read more about them here: http://www.macresearch.org/dynamics-scrolling. Basically, they bounce once, when they hit the top, and then they are done. My bounce animation works more like the way a UIAlertView bounce works, right when it scales in. It overshoots, and then undershoots, and overshoots again, until it settles.
