### ISSUE TITLE
Small feedback about implementing the delegate to keep the modal layer in sync after the animation

### ISSUE THREAD

**Issue by JaviSoto** [khanlou/SKBounceAnimation#4]
Just a small feedback about doing this:

``` objc
bounceAnimation.removedOnCompletion = NO;
bounceAnimation.fillMode = kCAFillModeForwards;
```

It's kind of a pain in the ass to have to implement the delegate method just to fix this. Here's a better way to do it:
1. First think you do is set the value on the layer.
2. This will create an implicit animation, with the default action for the key, but:
3. You create and add the animation to the layer. This is going to replace the implicit animation (because it'll have the same key).

``` objc
NSString *keyPath = @"position.y";
[view.layer setValueForKeyPath:keyPath];

SKBounceAnimation *bounceAnimation = [SKBounceAnimation animationWithKeyPath:@"position.y"];
bounceAnimation.fromValue = [NSNumber numberWithFloat:view.center.x];
bounceAnimation.toValue = [NSNumber numberWithFloat:300];
bounceAnimation.duration = 0.5f;
bounceAnimation.numberOfBounces = 2;

[view.layer addAnimation:bounceAnimation forKey:keyPath];
```

**Comment by khanlou** [comment]
Ah, thanks, this is way better! Does it flicker before the animation starts?

**Comment by JaviSoto** [comment]
Yeah it's way simpler!

No it doesn't. It creates an animation, but it's inmediately replaced by the actual one right after, before the `CATransaction` gets to be commited, so you don't see anything weird.

If you wanted (again, not neccesary in this case) to prevent the implicit animation that happens when you do `setValue:forKey:`, you could always do:

``` objc
[CATransaction begin];
[CATransaction setDisableActions:YES];
[view.layer setValue:v forKeyPath:keyPath];
[CATransaction commit];
```

Feel free to close this issue :) I just wanted to give this small feedback. Maybe you want to update the README file.

**Comment by khanlou** [comment]
Yeah, I'm gonna close it, but I'm gonna update the app examples and the readme. Thanks much.

**Comment by JaviSoto** [comment]
My pleasure :)
