### ISSUE TITLE
Static Analyzer Potential Leak

### ISSUE THREAD

**Issue by bogardon** [khanlou/SKBounceAnimation#6]
![Screen Shot 2012-12-12 at 3 12 28 PM](https://f.cloud.github.com/assets/399782/9577/6ae95810-44b1-11e2-9927-77d9b72013db.png)

The problem is that the returned object is never released. Is this an actual issue?

**Comment by khanlou** [comment]
You may have an older version. As of 1.0.2 this bug should be fixed. Let me know if it persists and you are up to date.

**Comment by bogardon** [comment]
ah my apologies. i always forget to check the latest version T_T
