### ISSUE TITLE
Static declaration of 'creatPathFromXYValues' follows non-static declaration

### ISSUE THREAD

**Issue by iwiz** [khanlou/SKBounceAnimation#7]
Hi 
   I am new I want to apply spring bonus effect.I am try to compile your Demo but its give this issue  

   Static declaration of 'creatPathFromXYValues' follows non-static declaration 

 How can I fix it 
thanks

**Comment by khanlou** [comment]
You may have an issue with having imported the class twice, or something like that. Take a look at http://stackoverflow.com/questions/3148244/static-declaration-follows-non-static-declaration , maybe that will help you.
